tech_type: kubernetes
tags:
  - cAdvisor
  - kubernetes
  - hardware
  - google
icon: bi-google
data_source_and_docs:
  - title: cAdvisor Documentation
    url: https://github.com/google/cadvisor/blob/master/docs/storage/prometheus.md
asset_list:
  - asset_type: Collection
    name: kubernetes
    slug: kubernetes-collection
    file: k8s-collection.yaml
    config_required: "no"
    description: Please modify if necessary
  - asset_type: Team
    name: kubernetes
    slug: kubernetes-team
    file: k8s-team.yaml
    config_required: "no"
    description: Please modify if necessary
  - asset_type: Dashboard
    name: cAdvisor
    slug: cadvisor
    file: dashboards/cadvisor-dashboard.yaml
    config_required: "no"
    author: Chronosphere
    source: CS
    description:
      Cadvisor exposes container and hardware statistics as prometheus
      metrics out of the box. by default, these metrics are served under the /metrics
      http endpoint. this endpoint may be customized by setting the -prometheus_endpoint
      and -disable_metrics or -enable_metrics command-line flags.
  - asset_type: Dashboard
    name: K8s Jobs and CronJobs Overview
    slug: kubernetes-collection
    file: dashboards/k8s-jobs-and-cronjobs-overview-dashboard.yaml
    config_required: "no"
    author: Chronosphere
    source: CS
    description: Kube-state-metrics (KSM) is a simple service that listens to the Kubernetes API server and generates metrics about the state of the objects. It is not focused on the health of the individual Kubernetes components, but rather on the health of the various objects inside, such as deployments, nodes and pods.
