tech_type: kubernetes
tags:
  - cAdvisor
  - kubernetes
  - hardware
  - google
  - k8s
icon: bi-google
data_source_and_docs:
  - title: cAdvisor Documentation
    url: https://github.com/google/cadvisor/blob/master/docs/storage/prometheus.md
asset_list:
  - asset_type: Collection
    name: kubernetes
    slug: kubernetes-collection
    file: k8s-collection.yaml
    config_required: "no"
    description: Please modify if necessary
  - asset_type: Team
    name: kubernetes
    slug: kubernetes-team
    file: k8s-team.yaml
    config_required: "no"
    description: Please modify if necessary
  - asset_type: Dashboard
    name: cAdvisor
    slug: cadvisor
    file: dashboards/cadvisor-dashboard.yaml
    config_required: "no"
    author: Chronosphere
    source: CS
    description: Cadvisor exposes container and hardware statistics as prometheus
      metrics out of the box. by default, these metrics are served under the /metrics
      http endpoint. this endpoint may be customized by setting the -prometheus_endpoint
      and -disable_metrics or -enable_metrics command-line flags.
  - asset_type: Dashboard
    name: K8s Deployments Overview
    slug: k8s-collection
    file: dashboards/k8s-deployments-overview-dashboard.yaml
    config_required: 'no'
    author: Chronosphere
    source: CS
    description: Kube-state-metrics (KSM) is a simple service that listens to the Kubernetes API server and generates metrics about the state of the objects. It is not focused on the health of the individual Kubernetes components, but rather on the health of the various objects inside, such as deployments, nodes and pods.
  - asset_type: Dashboard
    name: K8s Jobs and CronJobs Overview
    slug: kubernetes-collection
    file: dashboards/k8s-jobs-and-cronjobs-overview-dashboard.yaml
    config_required: "no"
    author: Chronosphere
    source: CS
    description: Kube-state-metrics (ksm) is a simple service that listens to the
      kubernetes api server and generates metrics about the state of the objects.
      it is not focused on the health of the individual kubernetes components, but
      rather on the health of the various objects inside, such as deployments, nodes
      and pods.
  - asset_type: Dashboard
    name: K8s Daemonsets Overview
    slug: k8s-daemonsets-overview
    file: dashboards/k8s-daemonsets-overview-dashboard.yaml
    config_required: 'no'
    author: Chronosphere
    source: CS
    description: Kube-state-metrics (ksm) is a simple service that listens to the
      kubernetes api server and generates metrics about the state of the objects.
      it is not focused on the health of the individual kubernetes components, but
      rather on the health of the various objects inside, such as deployments, nodes
      and pods.
  - asset_type: Dashboard
    name: Kube State Metrics
    slug: kube-state-metrics
    file: dashboards/kube-state-metrics-dashboard.yaml
    config_required: 'no'
    author: Chronosphere
    source: CS
    description: Kube-state-metrics (ksm) is a simple service that listens to the
      kubernetes api server and generates metrics about the state of the objects.
      it is not focused on the health of the individual kubernetes components, but
      rather on the health of the various objects inside, such as deployments, nodes
      and pods.
  - asset_type: Dashboard
    name: Node Exporter
    slug: node-exporter
    file: dashboards/node-exporter-dashboard.yaml
    config_required: 'no'
    author: Chronosphere
    source: CS
    description: Node exporter is a prometheus exporter that collects system-level
      metrics from linux and unix-like systems, exposing them in a format that prometheus
      can scrape for monitoring purposes, including cpu usage, memory, disk i/o, and
      more.
  - asset_type: Dashboard
    name: Kubernetes / Views / Global
    slug: kubernetes--views--global
    file: dashboards/kubernetes--views--global-dashboard.yaml
    config_required: 'no'
    author: Chronosphere
    source: CS
    description: Kube-state-metrics (ksm) is a simple service that listens to the
      kubernetes api server and generates metrics about the state of the objects.
      it is not focused on the health of the individual kubernetes components, but
      rather on the health of the various objects inside, such as deployments, nodes
      and pods.
  - asset_type: Dashboard
    name: Kubernetes / Views / Namespaces
    slug: kubernetes--views--namespaces
    file: dashboards/kubernetes--views--namespaces-dashboard.yaml
    config_required: 'no'
    author: Chronosphere
    source: CS
    description: Kube-state-metrics (ksm) is a simple service that listens to the
      kubernetes api server and generates metrics about the state of the objects.
      it is not focused on the health of the individual kubernetes components, but
      rather on the health of the various objects inside, such as deployments, nodes
      and pods.
